
name: CodeGen

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Generate"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NewPlatform.Flexberry.Designer.CommandLine
        run: nuget install NewPlatform.Flexberry.Designer.CommandLine -Version 0.1.0-alpha03 -OutputDirectory gen

      - name: Code generation
        run: mono ./gen/NewPlatform.Flexberry.Designer.CommandLine.0.1.0-alpha03/tools/flexberry.exe ./GenConfig.fdg

        
